# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ex01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'
  
  # Pods for ex01

  target 'ex01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ex01UITests' do
    # Pods for testing
  end

end
